#!/usr/bin/env bash
set -euo pipefail

# ── Styling ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

ask() {
    local prompt="$1" default="${2:-}" answer
    if [[ -n "$default" ]]; then
        read -rp "$(echo -e "${BOLD}${prompt} [${default}]:${NC} ")" answer
        echo "${answer:-$default}"
    else
        read -rp "$(echo -e "${BOLD}${prompt}:${NC} ")" answer
        echo "$answer"
    fi
}

valid_alias() {
    [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9-]{0,62}$ ]] && [[ ! "$1" =~ -$ ]]
}

add_authorized_key() {
    local key="$1" file="$2"
    grep -qxF "$key" "$file" 2>/dev/null || printf '%s\n' "$key" >> "$file"
}

# ── Root / user detection ─────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    error "Run with sudo: sudo $0"
    exit 1
fi

ACTUAL_USER="${SUDO_USER:-$USER}"
if [[ "$ACTUAL_USER" == "root" ]]; then
    error "Run this with sudo as a normal user, not as root directly."
    exit 1
fi

ACTUAL_HOME=$(eval echo "~${ACTUAL_USER}")
CURRENT_ALIAS=$(cat /etc/hostname 2>/dev/null || uname -n)
CURRENT_ALIAS=${CURRENT_ALIAS%%.*}

# ── Intro ─────────────────────────────────────────────────────────────────────
echo -e "${BOLD}========================================${NC}"
echo -e "${BOLD}  SSH Network Node Setup${NC}"
echo -e "${BOLD}========================================${NC}"
echo ""
info "This turns this machine into one SSH-network node."
echo ""

while true; do
    NODE_ALIAS=$(ask "Name/alias for this machine" "$CURRENT_ALIAS")
    if valid_alias "$NODE_ALIAS"; then
        break
    fi
    warn "Use letters/numbers/dashes only; must not start or end with dash."
done

# ── Packages ──────────────────────────────────────────────────────────────────
info "Ensuring packages are installed..."
DEPS=(openssh fail2ban)
MISSING=()
for pkg in "${DEPS[@]}"; do
    pacman -Qi "$pkg" &>/dev/null || MISSING+=("$pkg")
done
if [[ ${#MISSING[@]} -gt 0 ]]; then
    pacman -S --noconfirm "${MISSING[@]}"
fi
ok "Dependencies ready."

# ── Hostname ──────────────────────────────────────────────────────────────────
info "Setting hostname to ${NODE_ALIAS}..."
hostnamectl set-hostname "$NODE_ALIAS" 2>/dev/null || printf '%s\n' "$NODE_ALIAS" > /etc/hostname
ok "Hostname configured."

# ── SSH directories / keys ────────────────────────────────────────────────────
SSH_DIR="${ACTUAL_HOME}/.ssh"
AUTHORIZED_KEYS="${SSH_DIR}/authorized_keys"
MACHINE_KEY="${SSH_DIR}/id_ed25519_${NODE_ALIAS}"
HARDENING_FILE="/etc/ssh/sshd_config.d/00-hardening.conf"

info "Preparing SSH directories..."
install -d -m 700 -o "$ACTUAL_USER" -g "$ACTUAL_USER" "$SSH_DIR"
touch "$AUTHORIZED_KEYS"
chown "$ACTUAL_USER:$ACTUAL_USER" "$AUTHORIZED_KEYS"
chmod 600 "$AUTHORIZED_KEYS"
install -d -m 755 /etc/ssh/sshd_config.d

info "Generating unique SSH server host keys if missing..."
ssh-keygen -A
ok "Server host keys ready."

info "Ensuring this node has a unique outbound client key..."
if [[ ! -f "$MACHINE_KEY" ]]; then
    sudo -u "$ACTUAL_USER" ssh-keygen -t ed25519 -C "${ACTUAL_USER}@${NODE_ALIAS}" -f "$MACHINE_KEY" -N ""
    ok "Generated ${MACHINE_KEY}"
else
    ok "Keeping existing ${MACHINE_KEY}"
fi
chmod 600 "$MACHINE_KEY"
chmod 644 "${MACHINE_KEY}.pub"

# The node trusts its own node key. Future clone-to-disk runs use this key as the
# source node identity and append clone node keys here.
NODE_PUB=$(cat "${MACHINE_KEY}.pub")
add_authorized_key "$NODE_PUB" "$AUTHORIZED_KEYS"
chown "$ACTUAL_USER:$ACTUAL_USER" "$AUTHORIZED_KEYS"
chmod 600 "$AUTHORIZED_KEYS"
ok "Authorized this node key for inbound SSH."

# ── sshd hardening ────────────────────────────────────────────────────────────
if [[ -f "$HARDENING_FILE" ]]; then
    cp "$HARDENING_FILE" "${HARDENING_FILE}.bak.$(date +%s)"
    info "Backed up existing ${HARDENING_FILE}."
fi
if [[ -f /etc/ssh/sshd_config && ! -f /etc/ssh/sshd_config.bak ]]; then
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
fi

info "Writing hardened key-only sshd config..."
cat > "$HARDENING_FILE" <<EOF
# SSH network node — key-only, internet-facing
# Generated by setup-ssh.sh on $(date +%Y-%m-%d)
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
AuthenticationMethods publickey
PubkeyAuthentication yes
PermitRootLogin no
PermitEmptyPasswords no
AllowUsers ${ACTUAL_USER}
MaxAuthTries 3
X11Forwarding no
EOF

sshd -t
ok "sshd config validates."

# ── fail2ban ──────────────────────────────────────────────────────────────────
info "Configuring fail2ban..."
cat > /etc/fail2ban/jail.local <<'EOF'
[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 3

[sshd]
enabled = true
backend = systemd
EOF

# ── Services ──────────────────────────────────────────────────────────────────
info "Enabling and starting services..."
systemctl enable sshd
systemctl restart sshd
systemctl enable --now fail2ban
systemctl restart fail2ban
ok "sshd and fail2ban are active."

LOCAL_IP=$(ip -4 route get 1 2>/dev/null | awk '{print $7; exit}' || echo "<this-machine-ip>")

echo ""
echo -e "${GREEN}${BOLD}========================================${NC}"
echo -e "${GREEN}${BOLD}  SSH node setup complete${NC}"
echo -e "${GREEN}${BOLD}========================================${NC}"
echo ""
echo "Node alias:       ${NODE_ALIAS}"
echo "Server SSH:       ${ACTUAL_USER}@${LOCAL_IP}:22"
echo "Node client key:  ${MACHINE_KEY}"
echo "Public key:"
echo "  ${NODE_PUB}"
echo ""
echo "Router next step for internet access:"
echo "  <external-port>/tcp → ${LOCAL_IP}:22"
echo ""
