#!/usr/bin/env bash
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

ask_yn() {
    local prompt="$1" default="${2:-n}"
    if [[ "$default" == "y" ]]; then
        read -rp "$(echo -e "${BOLD}${prompt} [Y/n]:${NC} ")" answer
        [[ "${answer:-y}" =~ ^[Yy]$ ]]
    else
        read -rp "$(echo -e "${BOLD}${prompt} [y/N]:${NC} ")" answer
        [[ "$answer" =~ ^[Yy]$ ]]
    fi
}

# ---------------------------------------------------------------------------
# Root check
# ---------------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root (sudo)."
    exit 1
fi

ACTUAL_USER="${SUDO_USER:-$USER}"
ACTUAL_HOME=$(eval echo "~${ACTUAL_USER}")

if [[ "$ACTUAL_USER" == "root" ]]; then
    error "Run this with sudo as a normal user, not as root directly."
    exit 1
fi

HOSTNAME=$(cat /etc/hostname 2>/dev/null || uname -n)

echo -e "${BOLD}========================================${NC}"
echo -e "${BOLD}  SSH Server Setup (Arch Linux)${NC}"
echo -e "${BOLD}========================================${NC}"
echo ""
info "Setting up SSH for user: ${BOLD}${ACTUAL_USER}${NC} on ${BOLD}${HOSTNAME}${NC}"
echo ""

# ---------------------------------------------------------------------------
# Dependency check & install
# ---------------------------------------------------------------------------
DEPS=(openssh fail2ban)
MISSING=()

for pkg in "${DEPS[@]}"; do
    if ! pacman -Qi "$pkg" &>/dev/null; then
        MISSING+=("$pkg")
    fi
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
    info "Installing missing packages: ${MISSING[*]}"
    pacman -S --noconfirm "${MISSING[@]}"
    ok "Packages installed."
else
    ok "All dependencies already installed."
fi

# ---------------------------------------------------------------------------
# Detect existing SSH setup
# ---------------------------------------------------------------------------
EXISTING_SETUP=false
HARDENING_FILE="/etc/ssh/sshd_config.d/00-hardening.conf"

if [[ -f "$HARDENING_FILE" ]]; then
    EXISTING_SETUP=true
    warn "Existing SSH hardening config detected at ${HARDENING_FILE}:"
    echo ""
    sed 's/^/    /' "$HARDENING_FILE"
    echo ""
fi

if systemctl is-active --quiet sshd; then
    if [[ "$EXISTING_SETUP" == false ]]; then
        EXISTING_SETUP=true
        warn "sshd is currently running."
    fi
fi

AUTHORIZED_KEYS="${ACTUAL_HOME}/.ssh/authorized_keys"
if [[ -f "$AUTHORIZED_KEYS" ]] && [[ -s "$AUTHORIZED_KEYS" ]]; then
    KEY_COUNT=$(wc -l < "$AUTHORIZED_KEYS")
    warn "Found ${KEY_COUNT} authorized key(s) in ${AUTHORIZED_KEYS}."
    EXISTING_SETUP=true
fi

if [[ "$EXISTING_SETUP" == true ]]; then
    echo ""
    warn "An existing SSH setup was detected (see above)."
    if ! ask_yn "Overwrite and reconfigure from scratch?"; then
        info "Aborted. No changes made."
        exit 0
    fi
    echo ""
fi

# ---------------------------------------------------------------------------
# Choose mode
# ---------------------------------------------------------------------------
echo -e "${BOLD}Connection type:${NC}"
echo "  1) Local only  — password auth, LAN access"
echo "  2) Remote       — key-based auth, internet-facing, hardened"
echo ""
read -rp "$(echo -e "${BOLD}Choose [1/2]:${NC} ")" MODE_CHOICE

case "$MODE_CHOICE" in
    1) MODE="local" ;;
    2) MODE="remote" ;;
    *)
        error "Invalid choice."
        exit 1
        ;;
esac

# ---------------------------------------------------------------------------
# Backup existing config
# ---------------------------------------------------------------------------
if [[ -f "$HARDENING_FILE" ]]; then
    cp "$HARDENING_FILE" "${HARDENING_FILE}.bak.$(date +%s)"
    info "Backed up existing hardening config."
fi

if [[ ! -f "/etc/ssh/sshd_config.bak" ]]; then
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
    info "Backed up original sshd_config."
fi

# ---------------------------------------------------------------------------
# LOCAL MODE
# ---------------------------------------------------------------------------
if [[ "$MODE" == "local" ]]; then
    info "Configuring local-only SSH with password auth..."

    cat > "$HARDENING_FILE" <<EOF
# SSH setup — local only (password auth)
# Generated by setup-ssh.sh on $(date +%Y-%m-%d)
PasswordAuthentication yes
PermitRootLogin no
AllowUsers ${ACTUAL_USER}
MaxAuthTries 5
PermitEmptyPasswords no
EOF

    echo ""
    info "Set a password for ${ACTUAL_USER}:"
    passwd "$ACTUAL_USER"
    echo ""

    # Enable and (re)start sshd
    systemctl enable sshd
    systemctl restart sshd
    ok "sshd enabled and restarted."

    # fail2ban
    cat > /etc/fail2ban/jail.local <<EOF
[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 5

[sshd]
enabled = true
backend = systemd
EOF

    systemctl enable --now fail2ban
    ok "fail2ban enabled (5 attempts / 10min → 1h ban)."

    echo ""
    echo -e "${GREEN}${BOLD}========================================${NC}"
    echo -e "${GREEN}${BOLD}  Local SSH setup complete!${NC}"
    echo -e "${GREEN}${BOLD}========================================${NC}"
    echo ""
    LOCAL_IP=$(ip -4 route get 1 2>/dev/null | awk '{print $7; exit}' || echo "<this-machine-ip>")
    echo -e "  Connect with: ${BOLD}ssh ${ACTUAL_USER}@${LOCAL_IP}${NC}"
    echo ""
    exit 0
fi

# ---------------------------------------------------------------------------
# REMOTE MODE
# ---------------------------------------------------------------------------
info "Configuring remote SSH with key-based auth..."
echo ""

SSH_DIR="${ACTUAL_HOME}/.ssh"
mkdir -p "$SSH_DIR"
chown "${ACTUAL_USER}:${ACTUAL_USER}" "$SSH_DIR"
chmod 700 "$SSH_DIR"
touch "$AUTHORIZED_KEYS"
chown "${ACTUAL_USER}:${ACTUAL_USER}" "$AUTHORIZED_KEYS"
chmod 600 "$AUTHORIZED_KEYS"

KEY_FILE="${SSH_DIR}/id_ed25519"
KEY_MODE=""

echo -e "${BOLD}Do you already have a public key from the machine that will connect?${NC}"
echo "  1) Yes — I'll paste it  (use this if setting up remotely via SSH)"
echo "  2) No  — generate one   (use this if you're at this machine physically)"
echo ""
read -rp "$(echo -e "${BOLD}Choose [1/2]:${NC} ")" KEY_CHOICE

case "$KEY_CHOICE" in
    1) KEY_MODE="paste" ;;
    2) KEY_MODE="generate" ;;
    *)
        error "Invalid choice."
        exit 1
        ;;
esac

if [[ "$KEY_MODE" == "paste" ]]; then
    # ---------------------------------------------------------------------------
    # Paste flow — key lives on the client, user provides the public half
    # ---------------------------------------------------------------------------
    echo ""
    info "On the connecting machine, run this if you haven't already:"
    echo -e "     ${YELLOW}ssh-keygen -t ed25519${NC}"
    echo ""
    info "Then paste the contents of ${YELLOW}~/.ssh/id_ed25519.pub${NC} from that machine:"
    echo ""
    read -rp "Public key: " PUB_KEY

    if [[ ! "$PUB_KEY" =~ ^ssh-ed25519[[:space:]] ]] && [[ ! "$PUB_KEY" =~ ^ssh-rsa[[:space:]] ]] && [[ ! "$PUB_KEY" =~ ^ecdsa-sha2[[:space:]] ]]; then
        error "That doesn't look like a valid public key. Expected ssh-ed25519, ssh-rsa, or ecdsa-sha2 prefix."
        exit 1
    fi

    if grep -qF "$PUB_KEY" "$AUTHORIZED_KEYS" 2>/dev/null; then
        ok "Public key already in authorized_keys."
    else
        echo "$PUB_KEY" >> "$AUTHORIZED_KEYS"
        ok "Public key added to authorized_keys."
    fi

else
    # ---------------------------------------------------------------------------
    # Generate flow — key pair created on server, user copies private key out
    # ---------------------------------------------------------------------------
    if [[ -f "$KEY_FILE" ]]; then
        warn "SSH key already exists at ${KEY_FILE}."
        if ask_yn "Generate a new key? (old one will be backed up)"; then
            mv "$KEY_FILE" "${KEY_FILE}.bak.$(date +%s)"
            mv "${KEY_FILE}.pub" "${KEY_FILE}.pub.bak.$(date +%s)" 2>/dev/null || true
            sudo -u "$ACTUAL_USER" ssh-keygen -t ed25519 -C "${ACTUAL_USER}@${HOSTNAME}" -f "$KEY_FILE" -N ""
            ok "New ed25519 key generated."
        else
            ok "Keeping existing key."
        fi
    else
        sudo -u "$ACTUAL_USER" ssh-keygen -t ed25519 -C "${ACTUAL_USER}@${HOSTNAME}" -f "$KEY_FILE" -N ""
        ok "ed25519 key generated at ${KEY_FILE}"
    fi

    PUB_KEY=$(cat "${KEY_FILE}.pub")
    if grep -qF "$PUB_KEY" "$AUTHORIZED_KEYS" 2>/dev/null; then
        ok "Public key already in authorized_keys."
    else
        echo "$PUB_KEY" >> "$AUTHORIZED_KEYS"
        ok "Public key added to authorized_keys."
    fi
fi

# Write hardened sshd config
cat > "$HARDENING_FILE" <<EOF
# SSH setup — remote (key-based auth, hardened)
# Generated by setup-ssh.sh on $(date +%Y-%m-%d)
PasswordAuthentication no
PermitRootLogin no
AllowUsers ${ACTUAL_USER}
MaxAuthTries 3
PubkeyAuthentication yes
PermitEmptyPasswords no
EOF

ok "Hardened sshd config written to ${HARDENING_FILE}"

# Validate config
if sshd -t; then
    ok "sshd config validates."
else
    error "sshd config validation failed! Restoring backup."
    if [[ -f "${HARDENING_FILE}.bak."* ]]; then
        cp "${HARDENING_FILE}.bak."* "$HARDENING_FILE"
    else
        rm -f "$HARDENING_FILE"
    fi
    exit 1
fi

# Enable and (re)start sshd
systemctl enable sshd
systemctl restart sshd
ok "sshd enabled and restarted."

# fail2ban
cat > /etc/fail2ban/jail.local <<EOF
[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 3

[sshd]
enabled = true
backend = systemd
EOF

systemctl enable --now fail2ban
systemctl restart fail2ban
ok "fail2ban enabled (3 attempts / 10min → 1h ban)."

# ---------------------------------------------------------------------------
# Summary & next steps
# ---------------------------------------------------------------------------
LOCAL_IP=$(ip -4 route get 1 2>/dev/null | awk '{print $7; exit}' || echo "<this-machine-ip>")

echo ""
echo -e "${GREEN}${BOLD}========================================${NC}"
echo -e "${GREEN}${BOLD}  Remote SSH setup complete!${NC}"
echo -e "${GREEN}${BOLD}========================================${NC}"
echo ""
echo -e "${BOLD}What was configured on this machine:${NC}"
echo "  - Key-based auth only (passwords disabled)"
echo "  - Root login disabled"
echo "  - Only user '${ACTUAL_USER}' can log in"
echo "  - fail2ban active (3 failures → 1h ban)"
echo "  - sshd running and enabled on boot"
echo ""
echo -e "${BOLD}${CYAN}── Next steps ──${NC}"
echo ""

STEP=1

if [[ "$KEY_MODE" == "generate" ]]; then
    echo -e "  ${BOLD}${STEP}. Copy the private key to the connecting machine:${NC}"
    echo ""
    echo -e "     From the connecting machine, run:"
    echo -e "     ${YELLOW}scp ${ACTUAL_USER}@${LOCAL_IP}:${KEY_FILE} ~/.ssh/id_ed25519_${HOSTNAME}${NC}"
    echo ""
    echo -e "     Or copy the key contents manually:"
    echo -e "     ${YELLOW}# Copy ${KEY_FILE} to the connecting machine's ~/.ssh/${NC}"
    echo ""
    STEP=$((STEP + 1))
fi

echo -e "  ${BOLD}${STEP}. Set up port forwarding on your router:${NC}"
echo ""
echo -e "     Forward an external port to this machine's SSH:"
echo -e "     ${YELLOW}<your-chosen-port>${NC} (TCP) → ${YELLOW}${LOCAL_IP}:22${NC}"
echo ""
echo -e "     Use a high, non-standard port (e.g. 48222) to avoid scanners."
echo ""
STEP=$((STEP + 1))

echo -e "  ${BOLD}${STEP}. Configure SSH on the connecting machine:${NC}"
echo ""
echo -e "     Add to ${YELLOW}~/.ssh/config${NC} on the connecting machine:"
echo ""
echo -e "     ${YELLOW}Host ${HOSTNAME}-remote${NC}"
echo -e "     ${YELLOW}    HostName <your-public-ip-or-domain>${NC}"
echo -e "     ${YELLOW}    User ${ACTUAL_USER}${NC}"
echo -e "     ${YELLOW}    Port <your-chosen-port>${NC}"
if [[ "$KEY_MODE" == "generate" ]]; then
    echo -e "     ${YELLOW}    IdentityFile ~/.ssh/id_ed25519_${HOSTNAME}${NC}"
fi
echo ""
STEP=$((STEP + 1))

echo -e "  ${BOLD}${STEP}. Dynamic IP? Set up DDNS:${NC}"
echo ""
echo -e "     If your ISP assigns a dynamic IP (check router WAN settings),"
echo -e "     use a DDNS updater so your domain always points to the right IP."
echo -e "     See: ${YELLOW}https://github.com/Yeyito777/DNSimple-config${NC}"
echo ""
